spring:
  application:
    name: chirp-backend

  data:
    redis:
      host: "redis-14672.c341.af-south-1-1.ec2.redns.redis-cloud.com"
      username: "default"
      password: ${REDIS_PASSWORD}
      port: 14672

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: postgres.peasjtlgbvsynnirqhyk
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 256
        preparedStatementCacheMiB: 5

        tcpKeepAlive: true
        socketTimeout: 10
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    host: localhost
    port: 1025
    username:
    password:

  rabbitmq:
    host: dog.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: qkhhnyzq
    ssl:
      enabled: true
    virtual-host: qkhhnyzq
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}

chirp:
  email:
    from: no-reply@chirp.com
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx IP when using docker
    - "10.0.0.5/32" # nginx server IP if it's on a separate machine