spring:
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: false

chirp:
  email:
    url: "To determine later"
  rate-limit:
    ip:
      apply-limit: true